### ISSUE TITLE
Comments in step_U! are unclear

### ISSUE THREAD

**Issue by rafferrari** [glwagner/PriceWellerPinkel.jl#1]
https://github.com/glwagner/PriceWellerPinkel.jl/blob/f4dfa1bc9b251bef83bd64b003ad94e1942a2a70/src/integrate.jl#L71

Please define `Gz` in the comments.

**Comment by glwagner** [comment]
@rafferrari See if my changes suit you!

**Comment by rafferrari** [comment]
Not sure I saw any changes.
