### ISSUE TITLE
PP example

### ISSUE THREAD

**Issue by rafferrari** [glwagner/PriceWellerPinkel.jl#14]
I assume that the comparison between the PP example and Kato and Phillips could be improved by changing the constants kappa_1 and nu_1. How were the parameters chosen?

**Comment by glwagner** [comment]
I didn't go to too much effort --- I just changed the background values to molecular diffusivity (assuming this might be appropriate at the small scales of Kato and Phillips), and kept the rest the same.

[P&P](https://journals.ametsoc.org/doi/pdf/10.1175/1520-0485%281981%29011%3C1443%3APOVMIN%3E2.0.CO%3B2) hand-turned their parameters to match measurements of equatorial temperature and velocity structure in varying wind conditions.

Note that we do get the correct time dependence (sqrt[t]), we just don't get the right factor out in front.

Maybe by triangulating parameters to match both a convection experiment and a Kato-Phillips-like experiment we could obtain 'optimal' values for both convection and wind-mixing.

I'm worried, though, that P&P is a little too simple. It's hard to imagine how one choice of parameters would be appropriate across a wide range of forcing conditions...

**Comment by glwagner** [comment]
I'll open a PR and change the parameters systematically in the same way that P&P do in their original paper (see their Table 1) --- maybe we will learn something!

**Comment by rafferrari** [comment]
I agree that PP is probably too limited to capture all turbulence regimes. However Price-Weller-Pinkel use a Ri based model and claims that it successfully reproduces observations of mixed layer evolution in various regimes, so it may be worth a shot.
