### ISSUE TITLE
mean temperature balance in KPP example

### ISSUE THREAD

**Issue by sandreza** [glwagner/PriceWellerPinkel.jl#19]
In the KPP example the mean temperature should decrease linearly in time to match results from LES simulations. It seems that it has a nonlinear dependence. Furthermore the temperature growth rate (ignoring the fact that it isn't linear) seems to be of the order
-1.5628861651764384e-9 [Celcius  per second]
whereas it should be of the order
-1.915224652202957e-7 [Celcius per second]

Changing to different parameter regimes seems to alleviate this issue, but it isn't clear to me why this is the case.

**Comment by ali-ramadhan** [comment]
Is this to reproduce the results from Van Roekel et al. (2018)?

Out of curiousity, is there a _truth_ value from theory that we are expecting or are the LES simulations the truth here?

**Comment by sandreza** [comment]
There is a truth value from theory that we expect. The slope should be the (flux_top - flux_bottom)/Lz where Lz is the domain size. Specifically in this case,
letting the model constants be (in SI units)
p0 = 1035.0, the reference density
Cp = 3992.0, specific heat capacity of water
kappa = 10^(-4), numerical diffusion
\gamma = 0.01, imposed temperature gradient at the bottom, [kelvin per meter]
Q = 75 watts per meter squared surface cooling,
flux_bottom = kappa * \gamma
flux_top = Q / (p0 * Cp)
Lz = 100, domain size
we expect
-1.915224652202957e-7  = (-75 / (1035.0 * 3992.0) - 10^(-4) * 0.01)/100

**Comment by ali-ramadhan** [comment]
Thanks for the explanation! Would make a great test for https://github.com/climate-machine/Oceananigans.jl/issues/136

**Comment by glwagner** [comment]
We do use this test in Oceananigans when testing whether flux boundary conditions work correctly... ?

I’ll write a simple flux test case for all the modules in OceanTurb.

**Comment by sandreza** [comment]
I checked the Oceananigans equivalent and it seemed correct to within 6 decimal places. Since I am just taking a naive mean of the temperature profile I suspect that this could just be a discretization / quadrature error

**Comment by glwagner** [comment]
I found the bug --- it was the way I was updating the ghost cell values. It's fixed now by #21. 

We may want to further abstract the equation specification system to make sure little bugs like this are less likely in the future.
