### ISSUE TITLE
Reduce boiler plate in KPP implementation

### ISSUE THREAD

**Issue by glwagner** [glwagner/PriceWellerPinkel.jl#3]
There is a lot of boiler plate in the implementation of KPP:

https://github.com/glwagner/OceanTurb.jl/blob/e2f51ea733210423a1f74eb8c81a034d216d63a0/src/k_profile_parameterization.jl#L131

How can we reduce all the code duplication? Macros that replicate a function definition pattern, or perhaps a better type system for boundary conditions?

**Comment by ali-ramadhan** [comment]
Macros seem like the obvious solution and would definitely help but maybe if it's just 4 repetitions it might not be worth the sacrifice in readability? If it was like 6+ repetitions then definitely macros might look better?

**Comment by glwagner** [comment]
Not worth the sacrifice in readability.
