### ISSUE TITLE
Flux Output

### ISSUE THREAD

**Issue by sandreza** [glwagner/PriceWellerPinkel.jl#61]
Would it be possible to define a convenience function that outputs the fluxes 

- K(z,h) \partial_z T 
- \kappa \partial_z T
and
\Phi (the nonlocal term)

all separately for the model? This would allow for other comparison metrics with respect to LES simulations

**Comment by glwagner** [comment]
I'll do this in two parts:

1. Add a function, something like `OceanTurb.diffusive_flux(field, model)` that returns a `FaceField` with `K_Phi \partial_z Phi` for the current state of `model` for any `field=:Phi`.

2. Add a function `OceanTurb.KPP.nonlocal_flux(tracer, model)` that returns a `FaceField` with the nonlocal flux  specifically for the `KPP` module that works with `tracer=:T` and `tracer=:S`.

As for the molecular flux, there is already a function `∂z`, so do we need a special function to compute `constant * ∂z(T)`? I think writing `q_molecular = kappa * ∂z(T)` should work. Let me know if it doesn't.

Let me know if that sounds good and I'll write those up. Should be quick.

**Comment by sandreza** [comment]
Those sound great!
