### ISSUE TITLE
Arbitrary forcing functions for fields

### ISSUE THREAD

**Issue by sandreza** [glwagner/PriceWellerPinkel.jl#66]
It would be nice to have an interface similar to Oceananigans.jl 

https://climate-machine.github.io/Oceananigans.jl/latest/library/#Forcing-1

for forcing functions. In particular, it is important to have radiative heating in the upper ocean when including the effects of a diurnal cycle.

**Comment by glwagner** [comment]
Resolved by commit

https://github.com/glwagner/OceanTurb.jl/commit/635c6e84b99a53da17943e5eff9ffc3a328cfc49

@sandreza, please feel free to submit an example that uses the forcing functions when possible.

**Comment by glwagner** [comment]
Note, the new forcing functions have the signature

```julia
u_forcing(model, i) = # something
```
where `model` is `KPP.Model` or `ModularKPP.Model` depending on the module being used, and `i` indicates the index at which the forcing is applied.

To instantiate, use the keyword `forcing` in the model constructor:

```julia
model = KPP.Model(forcing=Forcing(U=u_forcing))
```

Please report bugs as they occur.
