### ISSUE TITLE
Require explicit 'grid' argument

### ISSUE THREAD

**Issue by glwagner** [glwagner/PriceWellerPinkel.jl#76]
It will be trivial to implement stretched grids, so this could be implemented at any time. To prepare for this I think all models should require the argument `grid`, rather than accepting `N` and `L`. Making this change will also allow us to change the semantics of grid construction more readily.

**Comment by sandreza** [comment]
Thinking towards the future, it may be a good idea to think of the grid in the context of what is necessary for a Discontinuous Galerkin implementation of OceanTurb. For example, the notion of a grid topology can be separated from the nodal points that the solution exists.
